### ISSUE TITLE
Create settings page

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#102]
What do we need for MVP?

- [x] Show me my pubkey and private key
- [x] Relays
- [ ] Extension shortcuts (make a highlight after selection + pull up side panel)
- [ ] Customize shortcut 

Related to [this](https://github.com/orgs/nostrdocs/projects/1/views/1?pane=issue&itemId=28976030)

**Comment by aassoiants** [comment]
^ added "customize shortcut" CC @Extheoisah @okjodom

**Comment by okjodom** [comment]
closed by #108 . We will add new issues when we iterate on the settings page
