### ISSUE TITLE
View the time and date a highlight was made

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#38]

**Comment by okjodom** [comment]
Needs design input. @nully0x, maybe you could start by adding the relevant data fields available to the UI?

> PS: We could redefine `IHighlight` type to be closer to the nostr event shape, then pass this to the UI. Example

```json
{
    "created_at": 1687315880,
    "content": "Newton’s theory of gravity allowed scientists to predict the future movements of objects like planets",
    "tags": [
      [
        "r",
        "https://www.blinkist.com/en/books/a-brief-history-of-time-en"
      ],
      [
        "range",
        "<SERIALIZED-RANGE-INFO>"
      ]
    ],
    "kind": 9802,
    "id": "e33d486f5332f78953b3f0578d0def1bb777d53f13fa323dd8e8c96d2116a4a3",
    "pubkey": "7e5230957749abdff0c5290e3b6b780579a5a18bccab3ff9364648a603e35cd9"
}
```

**Comment by nully0x** [comment]
Does this mean the date we present is a model from the nostr schema yea??

**Comment by okjodom** [comment]
As a first step, you could just add a `createdAt` field to `IHighlight` type, then render some UX for it in the menus
