### ISSUE TITLE
View highlights on page

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#39]
- [x] user sees all the highlights rendered on the canvas
- [x] user sees all the highlights within the side panel

**Comment by aassoiants** [comment]
Would look something like this: https://miro.com/app/board/uXjVMKbRYmg=/?moveToWidget=3458764554960456040&cot=14

Have both the user's highlights for the page, and (maybe dummy?) highlights from other users for that page to get their feedback on multiplayer highlights for the page

**Comment by aassoiants** [comment]
Global feed of highlights from npubs from Nostr integration lib

Full highlight details:

- [ ]  time
- [ ]  date
- [ ]  npub
- [ ]  domain

what else?

**Comment by aassoiants** [comment]
@okjodom who do we assign to this?

**Comment by okjodom** [comment]
closed after #121
