### ISSUE TITLE
Create user persona

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#41]
- [x] Product story
- [x] What problem is it solving for user's day to day life

_User story: I don’t think about the back end. It feels seamless. It always works, it’s always reliable. I can trust it to keep my notes. It adds to my web experience._

**Comment by okjodom** [comment]
Build for [Rabbit Hole Reuben](https://miro.com/app/board/uXjVMKbRYmg=/?moveToWidget=3458764557239381881&cot=14)

![image](https://github.com/nostrdocs/colighter/assets/11217077/c89dd917-f9ab-4907-96e1-4e63b0db8437)
