### ISSUE TITLE
Front End: Landing page experience

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#42]

**Comment by aassoiants** [comment]
See drafts here: https://miro.com/app/board/uXjVMKbRYmg=/

**Comment by okjodom** [comment]
initial landing page experience by @BalogunofAfrica : https://github.com/nostrdocs/colighter/pull/56

**Comment by aassoiants** [comment]
Wow y'all move fast! 

Here are my musings. I propose adding a third value prop in the Features section.

**Comment by aassoiants** [comment]
Point to how to download extension for beta testing

**Comment by okjodom** [comment]
we have a functional landing page at https://colighter.com. To be iterated upon
