### ISSUE TITLE
Publish highlight to Nostr

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#45]
When a user creates a new highlight on page, we should publish it to Nostr

**Comment by okjodom** [comment]
#115 adds functionality but disables it because we don't want to spam Nostr.

Question: Should we have an intermediate state allowing a user to validate and confirm the highlight before publish?

**Comment by aassoiants** [comment]
^ I've been thinking about this a lot

I think let's build out the screens for what this may look like and put it in front of users. 

Another solution is "batch publishing"?

**Comment by okjodom** [comment]
> > I think let's build out the screens for what this may look like and put it in front of users.
> 
> Ack. In the meanwhile, we just start with hot-publishing, yes?

#122 enables publishing to nostr
