### ISSUE TITLE
View my highlights for one single page

### ISSUE THREAD

**Issue by aassoiants** [nostrdocs/colighter#73]
- [ ] on canvas
- [x] within extension

Types of highlights
- [x] p tags
- [x] headers 
- [ ] over line breaks
- [ ] images

**Comment by aassoiants** [comment]
After a user makes a highlight on a page, need to be able to see a collection of those highlights, [for example](https://miro.com/app/board/uXjVMKbRYmg=/?moveToWidget=3458764554960456040&cot=14)

**Comment by aassoiants** [comment]
Ensure that can see the highlights on the canvas/ website (not just in the panel/ popup)

**Comment by okjodom** [comment]
merging with #39 to dedupe
